version: 2

defaults: &defaults
  docker:
    - image: docker:git
  
jobs:
  build_caddy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh caddy/
      - store_artifacts:
          path: ./caddy/build.log
  build_nginx:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh nginx/
      - store_artifacts:
          path: ./nginx/build.log

workflows:
  version: 2
  build_all:
    jobs:
      - build_caddy
      - build_nginx
