version: 2

defaults: &defaults
  docker:
    - image: docker:git
  
jobs:
  build_caddy:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh caddy/
  build_nginx:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: ./build.sh nginx/

workflows:
  version: 2
  build_all:
    jobs:
      - build_caddy
      - build_nginx
